name: CI

on:
   push:
     branches: [ "master" ]
   pull_request:
     branches: [ "master" ]

jobs:
   build:
     runs-on: ubuntu-latest
     env:
      config: 'Homolog'
      
     steps:
     - uses: actions/checkout@v3
     - name: Setup CI
       uses: actions/setup-dotnet@v2
       with:
         dotnet-version: 5.0.x
     
     # build dependencies
     - name: Restore dependencies
       run: dotnet restore
       
     # build project
     - name: Build
       run: dotnet build --no-restore
         
     # notify by slack    
     - name: Send GitHub Action trigger data to Slack workflow
       id: slack
       uses: slackapi/slack-github-action@v1.19.0
       env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
