name: CI

on:
   push:
     branches: [ "master" ]
   pull_request:
     branches: [ "master" ]

jobs:
   build:
     runs-on: ubuntu-latest
     env:
      config: 'Homolog'
      
     steps:
     - uses: actions/checkout@v3
     - name: Setup CI
       uses: actions/setup-dotnet@v2
       with:
         dotnet-version: 5.0.x
     
     # build dependencies
     - name: Restore dependencies
       run: dotnet restore
       
     # build project
     - name: Build
       run: dotnet build --no-restore
         
     # notify by slack    
     - name: Notification Slack
       uses: actions/setup-dotnet@v2
       env:
         SLACK_CHANNEL: pocdotnet
         SLACK_TITLE: Teste
         SLACK_USERNAME: BotCI
         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
         SLACK_MESSAGE: "This is your custom message." 
