name: CI

on:
   push:
     branches: [ "master" ]
   pull_request:
     branches: [ "master" ]

jobs:
   build:
     runs-on: ubuntu-latest
     env:
      config: 'Homolog'
      
     steps:
     - uses: actions/checkout@v3
     - name: Setup CI
       uses: actions/setup-dotnet@v2
       with:
         dotnet-version: 5.0.x
     
     # build dependencies
     - name: Restore dependencies
       run: dotnet restore
       
     # build project
     - name: Build
       run: dotnet build --no-restore
       
     # run tests
     - name: Integration Tests
       run: dotnet test --no-restore
         
     # notify by slack    
     - name: Notification Slack
       uses: rtCamp/action-slack-notify@v2
       if: ${{always()}}
       with:
        name: 'Integration Tests'
        path: ${{github.workspace}}/${{env.file_name}}
       env:
        SLACK_CHANNEL: pocdotnet
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Post Content :rocket:'
        SLACK_TITLE: Poc Teste integrado
        SLACK_USERNAME: TesteIntegrado
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
