name: CI

on:
   push:
     branches: [ "master" ]
   pull_request:
     branches: [ "master" ]

jobs:
   build:
     runs-on: ubuntu-latest
     env:
      config: 'Homolog'
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_CHANNEL: pocdotnet
      SLACK_TITLE: Agora vai
      SLACK_USERNAME: BotCI      
      SLACK_MESSAGE: "Poc de teste integrado"
      
     steps:
     - uses: actions/checkout@v3
     - name: Setup CI
       uses: actions/setup-dotnet@v2
       with:
         dotnet-version: 5.0.x
     
     # build dependencies
     - name: Restore dependencies
       run: dotnet restore
       
     # build project
     - name: Build
       run: dotnet build --configuration $config --no-restore
       
     # run tests
     - name: Integration Tests
       run: dotnet test --no-restore
         
     # notify by slack    
     - name: Notification Slack
     - uses: openhousepvt/slack@v1.3.2
       with: 
        status: ${{ job.status }}
       if: always()
