name: CI

on:
   push:
     branches: [ "master" ]
   pull_request:
     branches: [ "master" ]

jobs:
   build:
     runs-on: ubuntu-latest
     env:
      config: 'Homolog'
      
     steps:
     - uses: actions/checkout@v3
     - name: Setup CI
       uses: actions/setup-dotnet@v2
       with:
         dotnet-version: 5.0.x
     
     # build dependencies
     - name: Restore dependencies
       run: dotnet restore
       
     # build project
     - name: Build
       run: dotnet build --no-restore
       
     # run tests
     - name: Integration Tests
       run: dotnet test --no-restore
         
     # notify by slack    
     - name: Notification Slack
       uses: rtCamp/action-slack-notify@v2
       if: ${{failure()}}
       with:
        slack-message: 'GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}'
       env:
        SLACK_CHANNEL: pocdotnet
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://www.devision.com/wp-content/uploads/2017/10/devopsimage.png
        SLACK_TITLE: Teste com .NET
        SLACK_USERNAME: POCTesteIntegrado
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
